// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssets = `-- name: GetAssets :one
SELECT asset_id, ip_address, sysinfo_id, root_account_id, registered_at FROM assets
WHERE root_account_id = $1
`

func (q *Queries) GetAssets(ctx context.Context, rootAccountID pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssets, rootAccountID)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.IpAddress,
		&i.SysinfoID,
		&i.RootAccountID,
		&i.RegisteredAt,
	)
	return i, err
}
