// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package query

import (
	"context"
)

const createRootAccount = `-- name: CreateRootAccount :one
INSERT INTO root_accounts (
  email, username, password_hash, created_at, updated_at, email_verified_at
) VALUES (
  $1, $2, $3, EXTRACT(EPOCH FROM NOW()), EXTRACT(EPOCH FROM NOW()), NULL
)
RETURNING account_id, email, username, password_hash, created_at, updated_at, email_verified_at
`

type CreateRootAccountParams struct {
	Email        string
	Username     string
	PasswordHash string
}

func (q *Queries) CreateRootAccount(ctx context.Context, arg CreateRootAccountParams) (RootAccount, error) {
	row := q.db.QueryRow(ctx, createRootAccount, arg.Email, arg.Username, arg.PasswordHash)
	var i RootAccount
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}
