// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IamAccount struct {
	AccountID       int32
	RootAccountID   int32
	Email           string
	Username        string
	PasswordHash    string
	AccountStatus   string
	CreatedAt       pgtype.Int8
	UpdatedAt       pgtype.Int8
	EmailVerifiedAt pgtype.Int8
}

type IamAccountPermission struct {
	IamAccountID int32
	PermissionID int32
}

type Permission struct {
	PermissionID    int32
	IsAdministrator pgtype.Bool
	ViewAssets      pgtype.Bool
	ManageAssets    pgtype.Bool
	ViewModules     pgtype.Bool
	CreateModules   pgtype.Bool
	ManageModules   pgtype.Bool
	ViewScans       pgtype.Bool
	StartScans      pgtype.Bool
}

type RootAccount struct {
	AccountID       int32
	Email           string
	Username        string
	PasswordHash    string
	CreatedAt       pgtype.Int8
	UpdatedAt       pgtype.Int8
	EmailVerifiedAt pgtype.Int8
}
