// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: perms.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRolePermissions = `-- name: GetRolePermissions :one
SELECT p.permission_id, p.is_administrator, p.view_assets, p.manage_assets, p.view_modules, p.create_modules, p.manage_modules, p.view_scans, p.start_scans FROM roles r
JOIN
    roles_permissions rp ON r.role_id = rp.role_id
JOIN
    permissions p ON rp.permission_id = p.permission_id
WHERE
    r.role_name = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleName string) (Permission, error) {
	row := q.db.QueryRow(ctx, getRolePermissions, roleName)
	var i Permission
	err := row.Scan(
		&i.PermissionID,
		&i.IsAdministrator,
		&i.ViewAssets,
		&i.ManageAssets,
		&i.ViewModules,
		&i.CreateModules,
		&i.ManageModules,
		&i.ViewScans,
		&i.StartScans,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :one
SELECT p.permission_id, p.is_administrator, p.view_assets, p.manage_assets, p.view_modules, p.create_modules, p.manage_modules, p.view_scans, p.start_scans FROM iam_user_permissions iup
JOIN
    permissions p ON iup.permission_id = p.permission_id
JOIN
    iam_accounts ia ON iup.iam_account_id = ia.account_id
WHERE
    ia.username = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, username string) (Permission, error) {
	row := q.db.QueryRow(ctx, getUserPermissions, username)
	var i Permission
	err := row.Scan(
		&i.PermissionID,
		&i.IsAdministrator,
		&i.ViewAssets,
		&i.ManageAssets,
		&i.ViewModules,
		&i.CreateModules,
		&i.ManageModules,
		&i.ViewScans,
		&i.StartScans,
	)
	return i, err
}

const updateRolePermissions = `-- name: UpdateRolePermissions :exec
WITH updated_permission AS (
    UPDATE permissions
    SET
        is_administrator = $2,
        view_assets = $3,
        manage_assets = $4,
        view_modules = $5,
        create_modules = $6,
        manage_modules = $7,
        view_scans = $8,
        start_scans = $9
    WHERE
        permission_id = (
            SELECT permission_id
            FROM roles_permissions rp
            JOIN roles r ON rp.role_id = r.role_id
            WHERE r.role_name = $1
        )
    RETURNING permission_id
)
UPDATE roles_permissions rp
SET
    permission_id = updated_permission.permission_id
FROM updated_permission
JOIN roles r ON rp.role_id = r.role_id
WHERE r.role_name = $1
`

type UpdateRolePermissionsParams struct {
	RoleName        string
	IsAdministrator pgtype.Bool
	ViewAssets      pgtype.Bool
	ManageAssets    pgtype.Bool
	ViewModules     pgtype.Bool
	CreateModules   pgtype.Bool
	ManageModules   pgtype.Bool
	ViewScans       pgtype.Bool
	StartScans      pgtype.Bool
}

func (q *Queries) UpdateRolePermissions(ctx context.Context, arg UpdateRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, updateRolePermissions,
		arg.RoleName,
		arg.IsAdministrator,
		arg.ViewAssets,
		arg.ManageAssets,
		arg.ViewModules,
		arg.CreateModules,
		arg.ManageModules,
		arg.ViewScans,
		arg.StartScans,
	)
	return err
}

const updateUserPermissions = `-- name: UpdateUserPermissions :exec
WITH updated_permission AS (
    UPDATE permissions
    SET
        is_administrator = $2,
        view_assets = $3,
        manage_assets = $4,
        view_modules = $5,
        create_modules = $6,
        manage_modules = $7,
        view_scans = $8,
        start_scans = $9
    WHERE
        permission_id = (
            SELECT permission_id
            FROM iam_user_permissions iup
            JOIN iam_accounts ia ON iup.iam_account_id = ia.account_id
            WHERE ia.username = $1
        )
    RETURNING permission_id
)
UPDATE iam_user_permissions iup
SET
    permission_id = updated_permission.permission_id
FROM updated_permission
JOIN iam_accounts ia ON iup.iam_account_id = ia.account_id
WHERE ia.username = $1
`

type UpdateUserPermissionsParams struct {
	Username        string
	IsAdministrator pgtype.Bool
	ViewAssets      pgtype.Bool
	ManageAssets    pgtype.Bool
	ViewModules     pgtype.Bool
	CreateModules   pgtype.Bool
	ManageModules   pgtype.Bool
	ViewScans       pgtype.Bool
	StartScans      pgtype.Bool
}

func (q *Queries) UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) error {
	_, err := q.db.Exec(ctx, updateUserPermissions,
		arg.Username,
		arg.IsAdministrator,
		arg.ViewAssets,
		arg.ManageAssets,
		arg.ViewModules,
		arg.CreateModules,
		arg.ManageModules,
		arg.ViewScans,
		arg.StartScans,
	)
	return err
}
