// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.5
// source: internal/proto/agent_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HardwareInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonData string `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // The JSON string containing hardware info
}

func (x *HardwareInfoRequest) Reset() {
	*x = HardwareInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfoRequest) ProtoMessage() {}

func (x *HardwareInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfoRequest.ProtoReflect.Descriptor instead.
func (*HardwareInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *HardwareInfoRequest) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type HardwareInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Response message from the server
}

func (x *HardwareInfoResponse) Reset() {
	*x = HardwareInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfoResponse) ProtoMessage() {}

func (x *HardwareInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfoResponse.ProtoReflect.Descriptor instead.
func (*HardwareInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *HardwareInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // Name of the script
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // The script to be executed
}

func (x *ActionsRequest) Reset() {
	*x = ActionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsRequest) ProtoMessage() {}

func (x *ActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsRequest.ProtoReflect.Descriptor instead.
func (*ActionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *ActionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionsRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ActionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // Name of the script
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Status of the script transfer
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"` // Output of the script
	Error  string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`   // Error message if any
}

func (x *ActionsResponse) Reset() {
	*x = ActionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsResponse) ProtoMessage() {}

func (x *ActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsResponse.ProtoReflect.Descriptor instead.
func (*ActionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *ActionsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActionsResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ActionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // Message to be sent
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // Message to be sent
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TrivyReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`       // Message to be sent
	Path       string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`             // Path to scan
	Arguements string `protobuf:"bytes,3,opt,name=arguements,proto3" json:"arguements,omitempty"` // Arguments for the scan
}

func (x *TrivyReportRequest) Reset() {
	*x = TrivyReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrivyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrivyReportRequest) ProtoMessage() {}

func (x *TrivyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrivyReportRequest.ProtoReflect.Descriptor instead.
func (*TrivyReportRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *TrivyReportRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrivyReportRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TrivyReportRequest) GetArguements() string {
	if x != nil {
		return x.Arguements
	}
	return ""
}

type TrivyReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonData string `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // The JSON string containing the Trivy report
	Status   string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                     // Response message from the server
}

func (x *TrivyReportResponse) Reset() {
	*x = TrivyReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_agent_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrivyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrivyReportResponse) ProtoMessage() {}

func (x *TrivyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrivyReportResponse.ProtoReflect.Descriptor instead.
func (*TrivyReportResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *TrivyReportResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

func (x *TrivyReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_proto_agent_service_proto protoreflect.FileDescriptor

var file_internal_proto_agent_service_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x32, 0x0a, 0x13, 0x48, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x30,
	0x0a, 0x14, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x3e, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x6b, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2a, 0x0a,
	0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2b, 0x0a, 0x11, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x62, 0x0a, 0x12, 0x54, 0x72, 0x69, 0x76, 0x79, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x72,
	0x67, 0x75, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x72, 0x67, 0x75, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4a, 0x0a, 0x13, 0x54, 0x72,
	0x69, 0x76, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xaf, 0x02, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x13, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x0d, 0x53, 0x65,
	0x6e, 0x64, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0f,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x69, 0x76, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x72, 0x69, 0x76, 0x79, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x72, 0x69, 0x76, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x79, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6c, 0x4e,
	0x79, 0x78, 0x2f, 0x73, 0x79, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6c, 0x2d, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_agent_service_proto_rawDescOnce sync.Once
	file_internal_proto_agent_service_proto_rawDescData = file_internal_proto_agent_service_proto_rawDesc
)

func file_internal_proto_agent_service_proto_rawDescGZIP() []byte {
	file_internal_proto_agent_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_agent_service_proto_rawDescData)
	})
	return file_internal_proto_agent_service_proto_rawDescData
}

var file_internal_proto_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_agent_service_proto_goTypes = []any{
	(*HardwareInfoRequest)(nil),  // 0: grpc.HardwareInfoRequest
	(*HardwareInfoResponse)(nil), // 1: grpc.HardwareInfoResponse
	(*ActionsRequest)(nil),       // 2: grpc.ActionsRequest
	(*ActionsResponse)(nil),      // 3: grpc.ActionsResponse
	(*HeartbeatRequest)(nil),     // 4: grpc.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 5: grpc.HeartbeatResponse
	(*TrivyReportRequest)(nil),   // 6: grpc.TrivyReportRequest
	(*TrivyReportResponse)(nil),  // 7: grpc.TrivyReportResponse
}
var file_internal_proto_agent_service_proto_depIdxs = []int32{
	0, // 0: grpc.AgentService.SendHardwareInfo:input_type -> grpc.HardwareInfoRequest
	2, // 1: grpc.AgentService.BidirectionalStream:input_type -> grpc.ActionsRequest
	4, // 2: grpc.AgentService.SendHeartbeat:input_type -> grpc.HeartbeatRequest
	7, // 3: grpc.AgentService.SendTrivyReport:input_type -> grpc.TrivyReportResponse
	1, // 4: grpc.AgentService.SendHardwareInfo:output_type -> grpc.HardwareInfoResponse
	3, // 5: grpc.AgentService.BidirectionalStream:output_type -> grpc.ActionsResponse
	5, // 6: grpc.AgentService.SendHeartbeat:output_type -> grpc.HeartbeatResponse
	6, // 7: grpc.AgentService.SendTrivyReport:output_type -> grpc.TrivyReportRequest
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_agent_service_proto_init() }
func file_internal_proto_agent_service_proto_init() {
	if File_internal_proto_agent_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_agent_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HardwareInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HardwareInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ActionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ActionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TrivyReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_agent_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TrivyReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_agent_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_agent_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_agent_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_agent_service_proto_msgTypes,
	}.Build()
	File_internal_proto_agent_service_proto = out.File
	file_internal_proto_agent_service_proto_rawDesc = nil
	file_internal_proto_agent_service_proto_goTypes = nil
	file_internal_proto_agent_service_proto_depIdxs = nil
}
