// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.5
// source: internal/proto/bidirectional_comm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentService_SendHardwareInfo_FullMethodName    = "/grpc.AgentService/SendHardwareInfo"
	AgentService_BidirectionalStream_FullMethodName = "/grpc.AgentService/BidirectionalStream"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	SendHardwareInfo(ctx context.Context, in *HardwareInfo, opts ...grpc.CallOption) (*HardwareResponse, error)
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (AgentService_BidirectionalStreamClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) SendHardwareInfo(ctx context.Context, in *HardwareInfo, opts ...grpc.CallOption) (*HardwareResponse, error) {
	out := new(HardwareResponse)
	err := c.cc.Invoke(ctx, AgentService_SendHardwareInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (AgentService_BidirectionalStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_BidirectionalStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceBidirectionalStreamClient{stream}
	return x, nil
}

type AgentService_BidirectionalStreamClient interface {
	Send(*ReceiveScript) error
	Recv() (*ScriptResponse, error)
	grpc.ClientStream
}

type agentServiceBidirectionalStreamClient struct {
	grpc.ClientStream
}

func (x *agentServiceBidirectionalStreamClient) Send(m *ReceiveScript) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceBidirectionalStreamClient) Recv() (*ScriptResponse, error) {
	m := new(ScriptResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	SendHardwareInfo(context.Context, *HardwareInfo) (*HardwareResponse, error)
	BidirectionalStream(AgentService_BidirectionalStreamServer) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) SendHardwareInfo(context.Context, *HardwareInfo) (*HardwareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHardwareInfo not implemented")
}
func (UnimplementedAgentServiceServer) BidirectionalStream(AgentService_BidirectionalStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_SendHardwareInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HardwareInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendHardwareInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SendHardwareInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendHardwareInfo(ctx, req.(*HardwareInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).BidirectionalStream(&agentServiceBidirectionalStreamServer{stream})
}

type AgentService_BidirectionalStreamServer interface {
	Send(*ScriptResponse) error
	Recv() (*ReceiveScript, error)
	grpc.ServerStream
}

type agentServiceBidirectionalStreamServer struct {
	grpc.ServerStream
}

func (x *agentServiceBidirectionalStreamServer) Send(m *ScriptResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceBidirectionalStreamServer) Recv() (*ReceiveScript, error) {
	m := new(ReceiveScript)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHardwareInfo",
			Handler:    _AgentService_SendHardwareInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidirectionalStream",
			Handler:       _AgentService_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/bidirectional_comm.proto",
}
