name: syntinel-server
services:
  syntinel-server:
    container_name: syntinel-server
    image: syntinel-server:latest
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - APP_ENV=
      - APP_PORT=
      - APP_CONFIG_PATH=
      - REDIS_URL=
      - DATABASE_URL=postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@postgres:5432/${POSTGRESQL_DB}?sslmode=disable
      - CSRF_SECRET=
      - DATA_PATH=
    ports:
      - 8080:8080
    volumes:
      - syntinel_data:/app/data/
    restart: always

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data

  postgres:
    container_name: timescaledb 
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  syntinel_data:
  dragonflydata:
  postgres_data:

