name: syntinel-server
services:
  syntinel-server:
    container_name: syntinel-server
    image: syntinel-server:latest
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - APP_ENV=
      - APP_PORT=
      - APP_CONFIG_PATH=
      - REDIS_URL=
      - DATABASE_URL=
      - CSRF_SECRET=
      - DATA_PATH=
    ports:
      - 8080:8080
    volumes:
      - ~/syntinel-server/:/app/data/
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ~/syntinel-server/redis_data:/data
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - 5432:5432
    volumes:
      - ~/syntinel-server/postgres_data:/var/lib/postgresql/data
    restart: always
