services:
  syntinel-server:
    container_name: syntinel-server
    image: syntinel-server:latest
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - APP_ENV=production
      - APP_PORT=8080
      - APP_CONFIG_PATH=/app/data/config.yaml
      - REDIS_URL=redis:6379
      - DATABASE_URL=postgres://syntinel:syntinel@postgres:5432/syntinel?sslmode=disable
      - CSRF_SECRET=DEFAULT_SECRET_CHANGE_THIS
      - TLS_CERT_PATH=/app/data/certs/server_cert.pem
      - TLS_KEY_PATH=/app/data/certs/server_key.pem
      - ECDSA_PUBLIC_KEY_PATH=/app/data/ecdsa_public.pem
      - ECDSA_PRIVATE_KEY_PATH=/app/data/ecdsa_private.pem
    ports:
      - 8080:8080
    networks:
      - syntinel-network
    volumes:
      - /srv/syntinel-server:/app/data
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - /srv/syntinel-server/redis_data:/data
    networks:
      - syntinel-network
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=syntinel
      - POSTGRES_PASSWORD=syntinel
      - POSTGRES_DB=syntinel
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - syntinel-network
    volumes:
      - /srv/syntinel-server/postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  syntinel-network:
    driver: bridge
