// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/gRPC_server/hw_info.proto

package hw_info

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HwInfo_GetInfo_FullMethodName = "/gRPC.hw_info/GetInfo"
)

// HwInfoClient is the client API for HwInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HwInfoClient interface {
	GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error)
}

type hwInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewHwInfoClient(cc grpc.ClientConnInterface) HwInfoClient {
	return &hwInfoClient{cc}
}

func (c *hwInfoClient) GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoReply)
	err := c.cc.Invoke(ctx, HwInfo_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HwInfoServer is the server API for HwInfo service.
// All implementations must embed UnimplementedHwInfoServer
// for forward compatibility.
type HwInfoServer interface {
	GetInfo(context.Context, *InfoRequest) (*InfoReply, error)
	mustEmbedUnimplementedHwInfoServer()
}

// UnimplementedHwInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHwInfoServer struct{}

func (UnimplementedHwInfoServer) GetInfo(context.Context, *InfoRequest) (*InfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedHwInfoServer) mustEmbedUnimplementedHwInfoServer() {}
func (UnimplementedHwInfoServer) testEmbeddedByValue()                {}

// UnsafeHwInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HwInfoServer will
// result in compilation errors.
type UnsafeHwInfoServer interface {
	mustEmbedUnimplementedHwInfoServer()
}

func RegisterHwInfoServer(s grpc.ServiceRegistrar, srv HwInfoServer) {
	// If the following call pancis, it indicates UnimplementedHwInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HwInfo_ServiceDesc, srv)
}

func _HwInfo_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HwInfoServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HwInfo_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HwInfoServer).GetInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HwInfo_ServiceDesc is the grpc.ServiceDesc for HwInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HwInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gRPC.hw_info",
	HandlerType: (*HwInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _HwInfo_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/gRPC_server/hw_info.proto",
}
