name: sqlcheck
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@v1.4.0
      id: sqlcheck
      with:
        post-comment: false
        risk-level: 3
        verbose: true
        postfixes: |
          sql
          sqlx
          schema
        directories: |
          internal/database
    - name: Get output
      run: echo "Issues found in previous step"
      if: steps.sqlcheck.outputs.issue-found